################################################################################
# Fakeroot utilities
################################################################################

# gen_fstable_cmd() - File system specification table file generation command
#                     list
# $(1): path to file system specification file to generate
# $(2): name of variable holding file system specification string
#
# Output a shell command list suitable for generating a file system
# specification table file from string passed in argument.
#
# Warning: echo_multi_line_var_cmd() macro requires an advanced shell.
define gen_fstable_cmd
$(call log_action,FSTABLE,$(1)); \
$(call echo_multi_line_var_cmd,$($(strip $(2)))) > $(strip $(1))
endef

# gen_fakefs_cmd() - Fakeroot directory hierarchy generation command list
# $(1): path to root of directory hierarchy to generate
# $(2): path to file system specification file
# $(3): path to fakeroot environment file
# $(4): path to root of input directory hierarchy to generate $(1) from
#
# Output a shell command list suitable for generating a directory hierarchy
# from entries found under the specificied input root directory.
# Entries will be generated according to file system properties defined into the
# given file system specification file.
# Generation operations will be wrapped into a fakeroot environment to overcome
# permission issues when not running as root user.
#
# Note: the final touch command is required to update the output root directory
#       modification time with respect to the fakeroot environment file.
define gen_fakefs_cmd
$(call log_action,GENFAKE,$(1)); \
$(CRAFTER_SCRIPTDIR)/genfakefs.sh $(if $(Q),--quiet) \
                                  --fake $(strip $(3)) \
                                  $(strip $(1)) \
                                  $(strip $(4)) \
                                  $(strip $(2)) && \
touch $(strip $(1))
endef

# clean_fakefs_cmd() - Cleanup a directory hierarchy generated by gen_fakefs_cmd
# $(1): path to root of directory hierarchy to cleanup
# $(2): path to file system specification file
# $(3): path to fakeroot environment file
#
# Output a shell command list suitable for removing all filesystem entries
# generated by a gen_fakefs_cmd.
# Entries to remove will be read from the given file system specification file.
# Operations will be wrapped into a fakeroot environment to overcome permission
# issues when not running as root user.
define clean_fakefs_cmd
$(call log_action,CLEANFAKE,$(1)); \
if [ -f "$(strip $(3))" ] && [ -f "$(strip $(2))" ]; then \
	fakeroot -s $(3) -i $(3) -- \
		sh -ec \
		"tac $(2) | awk '{ print \$$2 }' | while read entry; do \
			if [ -L "$(strip $(1))/\$$entry" ]; then \
				rm -f "$(strip $(1))/\$$entry"; \
			elif [ -d "$(strip $(1))/\$$entry" ]; then \
				rmdir --ignore-fail-on-non-empty \
				      "$(strip $(1))/\$$entry"; \
			else \
				rm -f "$(strip $(1))/\$$entry"; \
			fi; \
		done"; \
fi
endef
